// <auto-generated />
using System;
using System.Collections.Generic;
using DojoFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DojoFlow.Infrastructure.Migrations
{
    [DbContext(typeof(DojoFlowDbContext))]
    [Migration("20260730224728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DojoFlow.Domain.Entities.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClaveKiosco")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoMensualidad")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<List<string>>("Disciplinas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Activo = true,
                            Apellido = "Llanes",
                            ClaveKiosco = 12345,
                            CostoMensualidad = 1500.00m,
                            Disciplinas = new List<string> { "MMA", "JiuJitsu" },
                            FechaInscripcion = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Carlos",
                            Telefono = "9991234567"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Activo = true,
                            Apellido = "Sosa",
                            ClaveKiosco = 98765,
                            CostoMensualidad = 850.00m,
                            Disciplinas = new List<string> { "Boxeo" },
                            FechaInscripcion = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "María",
                            Telefono = "9999876543"
                        });
                });

            modelBuilder.Entity("DojoFlow.Domain.Entities.Mensualidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Mensualidades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            AlumnoId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            EstadoActual = "Pendiente",
                            FechaGeneracion = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaVencimiento = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 1500.00m
                        });
                });

            modelBuilder.Entity("DojoFlow.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f90"),
                            ImagenUrl = "",
                            Nombre = "Cinturón (Todos los colores)",
                            StockActual = 10,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9001"),
                            ImagenUrl = "",
                            Nombre = "Guantes de 16 oz",
                            StockActual = 10,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2f3a-4b5c-6d7e8f900112"),
                            ImagenUrl = "",
                            Nombre = "Guantes de 14 oz",
                            StockActual = 10,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3a4b-5c6d-7e8f90011223"),
                            ImagenUrl = "",
                            Nombre = "Espinilleras Fighter Legend",
                            StockActual = 10,
                            StockMinimo = 2
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4b5c-6d7e-8f9001122334"),
                            ImagenUrl = "",
                            Nombre = "Bucales de GuardPro",
                            StockActual = 10,
                            StockMinimo = 4
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-5c6d-7e8f-900112233445"),
                            ImagenUrl = "",
                            Nombre = "Aguas",
                            StockActual = 10,
                            StockMinimo = 5
                        });
                });

            modelBuilder.Entity("DojoFlow.Domain.Entities.RegistroFinanciero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("IngresosMensualidades")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IngresosVentas")
                        .HasColumnType("numeric");

                    b.Property<string>("MesAnio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VentasRealizadas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MesAnio")
                        .IsUnique();

                    b.ToTable("RegistrosFinancieros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngresosMensualidades = 15000m,
                            IngresosVentas = 4500m,
                            MesAnio = "04-2026",
                            VentasRealizadas = 20
                        },
                        new
                        {
                            Id = 2,
                            IngresosMensualidades = 18500m,
                            IngresosVentas = 3200m,
                            MesAnio = "05-2026",
                            VentasRealizadas = 15
                        });
                });

            modelBuilder.Entity("DojoFlow.Domain.Entities.UsuarioCoach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetPinExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResetPinHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UsuariosCoach");
                });
#pragma warning restore 612, 618
        }
    }
}
